# This workflow runs HACS validation, tests, and linting.
name: CI & Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # Run weekly to catch any breaking changes from HACS or Home Assistant.
    - cron: "0 0 * * 0"

jobs:
  # This job is required for HACS to validate your integration.
  hacs_validation:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the code
        uses: "actions/checkout@v4"
      - name: HACS Validation Action
        uses: "hacs/action@main"
        with:
          category: "integration"

    # This job runs your own quality checks.
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Add this step to cache dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          # The path to the cache directory
          path: ~/.cache/pip
          # A key that identifies the cache. It changes when requirements_test.txt changes.
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_test.txt') }}
          # A fallback key if the primary key doesn't match
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Run linting with Ruff
        run: |
          ruff check .

      - name: Run tests with Pytest
        run: |
          pytest